### ISSUE TITLE
Osa 8.5 tehtävä Maksukortin Osa 3:ssa virheellinen esimerkkitulostus

### ISSUE THREAD

**Issue by dookieboo** [rage/ohjelmointi-22#37]
Esimerkkitulostus on väärin.
Kortilla on 10€ alussa, siihen lisätään 15€ + 10€ + 200€
Lopuksi kortilla on 235 euroa, ei 150 euroa, kuten esimerkkitulostus näyttää

**Comment by jussmaki** [comment]
Korjattu. Kiitos! :)
